//try And Catch syntax :-
try {
    let a; 
    console.log(a.length);
    console.log("hi there from inside the try");
}
catch(e) {
    console.log("inside catch statement");
}

console.log("hi there")